name: animated_cycler
description: A versatile Flutter widget that automatically cycles through items with smooth bidirectional animations. Perfect for tickers, banners, news feeds, and rotating content.
version: 1.0.0
homepage: https://github.com/BottlePumpkin/animated_cycler
repository: https://github.com/BottlePumpkin/animated_cycler
issue_tracker: https://github.com/BottlePumpkin/animated_cycler/issues
documentation: https://pub.dev/documentation/animated_cycler/latest/

topics:
  - widget
  - animation
  - carousel
  - ticker
  - banner

screenshots:
  - description: 'Vertical ranking ticker with smooth animation transitions'
    path: example/assets/screenshots/1.gif
  - description: 'Horizontal banner slider with product showcase'
    path: example/assets/screenshots/2.gif
  - description: 'Manual controls and interactive features'
    path: example/assets/screenshots/3.gif
  - description: 'Custom animation curves and timing demonstrations'
    path: example/assets/screenshots/4.gif

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section ensures no assets are included by default
flutter:
  # assets:
  # fonts:

# Analysis options for better code quality
# Create analysis_options.yaml for detailed linting rules